function getSides(num)
{
	//var num = prompt("Enter the number of sides");
  
  num = validateEntry(num);
  
  document.getElementById("final").innerHTML = num;
  
  
  var polygonName = getPolygonName(num);
  var phrase = "The item generated by " + num + " sides is a/an " + polygonName;
  
  document.getElementById("final").innerHTML = phrase;
  
}

function validateEntry(num)
{
	while(isNaN(num) || num < 3 || num > 8)
  {
  	alert("Enter another number");
    num = prompt("Enter the number of sides");
  }
  
  return num;
}

function getPolygonName(num)
{
	var listPoly = new Array("Triangle", "Square", "Pentagon", "Hexagon", "Septagon", "Octagon");
  return listPoly[num - 3];
}
